name: Backend build, test and deployment to thenanne.nl

on: 
  push:
    paths: ['.github/workflows/dotnetcore-backend.yml','backend/**']
    branches: [ master ]
  pull_request:
    paths: ['.github/workflows/dotnetcore-backend.yml','backend/**']
    branches: [ master ]

jobs:
  build-test-and-deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: Install dependencies
      working-directory: backend
      run: dotnet restore
    - name: Build
      working-directory: backend
      run: dotnet build --configuration Release --no-restore
    - name: Test
      working-directory: backend
      run: dotnet test --no-restore --verbosity normal
 #   - name: Upload artifact
 #     if: success()
 #     uses: actions/upload-artifact@v1.0.0
 #     with:
 #       # Artifact name
 #       name: backend
 #       # Directory containing files to upload
 #       path: backend/Pubquiz.WebApi/bin/Release/netcoreapp3.1
    - name: dotnet publish
      working-directory: backend
      run: dotnet publish -c Release -o ${{env.DOTNET_ROOT}}/myapp
    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v1
      with:
        app-name: 'thenanne-web'
        slot-name: 'production'
        publish-profile: ${{ secrets.THENANNE_WEB_PUBLISH_PROFILE }}
        package: ${{env.DOTNET_ROOT}}/myapp 
    - name: Notify slack success
      if: success()
      env:
        SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
      uses: voxmedia/github-action-slack-notify-build@v1
      with:
        channel: sourcecontrol
        status: SUCCESS
        color: good
    - name: Notify slack fail
      if: failure()
      env:
        SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
      uses: voxmedia/github-action-slack-notify-build@v1
      with:
        channel: sourcecontrol
        status: FAILED
        color: danger
